#!/bin/bash

FISH=/usr/local/bin/fish

if [ ! -e ${FISH} ]; then
    exit 0
fi

if [ ${SHELL} = ${FISH} ]; then
    exit 0
fi

echo "Configuring fish ..."
sudo bash -c "echo ${FISH} >> /etc/shells"
sudo chsh -s ${FISH}
