#!/bin/bash

CODE=/usr/local/bin/code

if [ $(uname) != "Darwin" ]; then
    exit 0
fi

if [ ! -e ${CODE} ]; then
    exit 0
fi

echo "Configuring VS Code ..."
SRCDIR=${HOME}/.config/Code/User
DSTDIR=${HOME}/Library/Application\ Support/Code/User
mkdir -p "${DSTDIR}"
ln -fs "${SRCDIR}/settings.json" "${DSTDIR}/settings.json"
