#!/bin/bash

if [ -z "$DOTINSTALL" ]; then
    exit 0
fi

echo "Installing tpm ..."
TPMDIR=${HOME}/.tmux/plugins/tpm

if [ ! -e ${TPMDIR} ]; then
    git clone https://github.com/tmux-plugins/tpm ${TPMDIR}
fi

${TPMDIR}/bin/install_plugins
